Sscs 10723 handling error issue
hmcts/sscs-ccd-definitions pull request #1009
Opened 2022-07-13 09:33 UTC by olyode

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/SSCS-10723

### Change description ###
Added handlingError to precondition with readyToList

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2022-07-13 11:22 UTC, dattipoeHMCTS requested changes
Needs the versions incremented

2022-07-13 11:22 UTC, ikirsanov approved these changes

2022-07-13 11:49 UTC, olyode commented
> Needs the versions incremented

@dattipoeHMCTS Is this version update correct? 5.14.28

2022-07-14 14:52 UTC, dattipoeHMCTS approved these changes

2022-07-28 15:14 UTC, merged