SSCS-10748: Add hiding conditions to date and time fields in hearings…
hmcts/sscs-ccd-definitions pull request #1010
Opened 2022-07-20 09:54 UTC by ikirsanov

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/SSCS-10748

### Change description ###
Added fields show condition for date and time in hearings(complex type)

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[ x] No
```

2022-07-21 12:39 UTC, TeaWithLucas approved these changes
You'll need to rebase and rebump the version number

2022-07-22 15:01 UTC, ss-evoco approved these changes

2022-07-27 08:30 UTC, dattipoeHMCTS commented on benefit/data/sheets/ComplexTypes/ComplexTypes.json
> +  {"LiveFrom": "10/03/2022", "ID": "hearingDetails", "ListElementCode": "hearingRoute", "FieldType": "FixedList", "FieldTypeParameter": "FL_hearingRoute", "ElementLabel": "Hearing Route", "SecurityCl
How come this is here now?

2022-07-27 13:00 UTC, ikirsanov commented on benefit/data/sheets/ComplexTypes/ComplexTypes.json
> +  {"LiveFrom": "10/03/2022", "ID": "hearingDetails", "ListElementCode": "hearingRoute", "FieldType": "FixedList", "FieldTypeParameter": "FL_hearingRoute", "ElementLabel": "Hearing Route", "SecurityCl
Forgot to remove this one.

2022-08-03 08:38 UTC, dattipoeHMCTS requested changes
Need to bump the version in CaseType and VERSION.yaml before merging

2022-08-03 08:53 UTC, dattipoeHMCTS approved these changes

2022-08-03 08:53 UTC, merged