SSCS-10506 Hearing Callback Fix for Ready to List
hmcts/sscs-ccd-definitions pull request #1012
Opened 2022-07-22 14:38 UTC by TeaWithLucas

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/SSCS-10506

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2022-07-22 15:33 UTC, JustMehmet approved these changes

2022-07-25 08:41 UTC, amittal89 approved these changes

2022-07-26 08:40 UTC, ss-evoco approved these changes

2022-07-26 09:09 UTC, dattipoeHMCTS requested changes
Version bumps too

2022-07-26 09:09 UTC, dattipoeHMCTS commented on benefit/data/sheets/CaseEvent/CaseEvent.json
> -    "CallBackURLSubmittedEvent": "${CCD_DEF_SSCS_CCD_ORCHESTRATOR_URL}/send",
Need to make sure this is regression tested by dev and QA

2022-08-05 09:30 UTC, closed without merging