SSCS-10806-Enable-Ready-for-list-event-for-Caseworkers-and-TCW-Registrars
hmcts/sscs-ccd-definitions pull request #1014
Opened 2022-08-05 14:32 UTC by bensonlievoco

…rars

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/SSCS-10806

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2022-08-12 09:03 UTC, amittal89 approved these changes

2022-08-12 10:14 UTC, DGordonV1 approved these changes

2022-08-16 09:20 UTC, TeaWithLucas requested changes
Can you bump the tag in version and the casetype sheet

2022-08-18 08:28 UTC, bensonlievoco commented
will dump the version after po review. thanks

2022-08-18 12:00 UTC, TeaWithLucas approved these changes

2022-09-07 13:29 UTC, ss-evoco approved these changes

2022-09-07 13:48 UTC, bensonlievoco commented
> Please fix Jenkins errors @bensonlievoco

it will not be fix, that usually error. please ignore that

2022-09-07 13:55 UTC, hgulv1 approved these changes

2022-09-07 14:18 UTC, merged