SSCS-10832 - Provide TCW’s permission to access ‘the process audio/vi…
hmcts/sscs-ccd-definitions pull request #1030
Opened 2022-09-12 09:33 UTC by hajam09

…deo evidence’ event

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2022-09-12 09:50 UTC, bensonlievoco approved these changes

2022-09-12 10:52 UTC, dattipoeHMCTS requested changes
Versions

2022-09-12 11:34 UTC, bensonlievoco approved these changes

2022-09-12 11:37 UTC, bensonlievoco commented
> Versions

it just going to test, can do the version bump after the po review

2022-09-12 13:45 UTC, dattipoeHMCTS submitted a review, later dismissed

2022-09-12 15:49 UTC, bensonlievoco approved these changes

2022-09-12 15:51 UTC, pk2453 submitted a review, later dismissed

2022-09-12 16:21 UTC, filippo-possenti-version1 approved these changes

2022-09-13 08:31 UTC, dattipoeHMCTS approved these changes

2022-09-14 07:24 UTC, closed without merging