SSCS-10562 update Child Support to Child Support Agency
hmcts/sscs-ccd-definitions pull request #1033
Opened 2022-09-15 10:20 UTC by pk2453

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/SSCS-10562

### Change description ###
Change one of FTA office from "Child Support" to "Child Support Agency"

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

2022-09-15 13:16 UTC, nickhill111 submitted a review, later dismissed

2022-09-16 08:22 UTC, nickhill111 requested changes

2022-09-16 08:22 UTC, nickhill111 commented on benefit/VERSION.yaml
> +
Remove whitespace. I'm about to deploy my ticket to 5.15.10 so might be good to bump this up again

2022-09-16 08:31 UTC, bensonlievoco approved these changes

2022-09-16 10:06 UTC, bensonlievoco submitted a review, later dismissed

2022-09-16 11:25 UTC, dattipoeHMCTS submitted a review, later dismissed

2022-11-02 11:34 UTC, hgulv1 approved these changes

2022-11-03 08:55 UTC, nickhill111 approved these changes

2022-11-25 11:25 UTC, amoslv1 approved these changes

2022-11-25 11:26 UTC, nickhill111 approved these changes

2022-12-06 13:55 UTC, merged