SSCS-10789 - TCW should be able to Action Postponement Request from N…
hmcts/sscs-ccd-definitions pull request #1037
Opened 2022-09-22 15:43 UTC by hajam09

…ext Steps

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

2022-09-27 15:49 UTC, hgulv1 submitted a review, later dismissed

2022-09-27 16:01 UTC, EliandroGV1 approved these changes

2022-09-28 09:58 UTC, ss-evoco submitted a review, later dismissed

2022-09-28 10:38 UTC, TeaWithLucas approved these changes

2022-09-30 13:16 UTC, nickhill111 submitted a review, later dismissed

2022-09-30 13:23 UTC, ss-evoco requested changes
You need to change the case type in CaseType.json file too.

2022-10-03 09:15 UTC, bensonlievoco approved these changes

2022-10-03 12:15 UTC, pk2453 submitted a review, later dismissed

2022-10-03 12:32 UTC, ss-evoco submitted a review, later dismissed

2022-10-04 07:20 UTC, ss-evoco submitted a review, later dismissed

2022-10-04 08:55 UTC, hgulv1 submitted a review, later dismissed

2022-10-04 16:01 UTC, TeaWithLucas approved these changes

2022-10-06 09:02 UTC, DGordonV1 submitted a review, later dismissed

2022-10-07 10:56 UTC, amoslv1 approved these changes

2022-10-10 09:35 UTC, bensonlievoco submitted a review, later dismissed

2022-10-12 08:02 UTC, EliandroGV1 submitted a review, later dismissed

2022-10-12 08:23 UTC, ss-evoco approved these changes

2022-10-24 13:00 UTC, TeaWithLucas submitted a review, later dismissed

2022-10-25 10:24 UTC, hgulv1 approved these changes

2022-10-25 10:27 UTC, EliandroGV1 approved these changes

2022-10-27 08:49 UTC, ss-evoco approved these changes

2022-10-27 09:18 UTC, merged