SSCS-10766 - Create Set Aside Granted Document  - CALL
hmcts/sscs-ccd-definitions pull request #1247
Opened 2023-03-24 15:22 UTC by DGordonV1

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/SSCS-10766
### Change description ###
Changes to ccd-def to allow postHearingReview actions for particular users (see auth changes).
**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x] No
```

2023-03-30 09:34 UTC, amoslv1 approved these changes

2023-04-03 08:20 UTC, hajam09 approved these changes

2023-04-03 08:21 UTC, hajam09 requested changes
Version bump please.

2023-04-03 08:23 UTC, AndreiTrushkov approved these changes

2023-04-03 08:36 UTC, hajam09 submitted a review, later dismissed

2023-04-03 09:39 UTC, AndreiTrushkov submitted a review, later dismissed

2023-04-17 08:09 UTC, amoslv1 approved these changes

2023-04-17 08:56 UTC, nickhill111 approved these changes

2023-04-17 10:44 UTC, nickhill111 commented
missing version bump

2023-08-15 07:56 UTC, nickhill111 approved these changes

2023-08-15 08:08 UTC, AndreiTrushkov approved these changes

2023-08-15 08:09 UTC, merged