Sscssi 252
hmcts/sscs-ccd-definitions pull request #1641
Opened 2024-06-27 21:31 UTC by pats-john

### Jira link (if applicable)

### Change description ###

### Checklist

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)
- [ ] Does this PR introduce a breaking change

2024-06-28 10:40 UTC, sanjayparekh-hmcts requested changes

2024-06-28 10:40 UTC, sanjayparekh-hmcts commented on Jenkinsfile_CNP
> +            env.IDAM_URL='https://idam-api.demo.platform.hmcts.net'
needs to be -demo not -aat

2024-06-28 15:20 UTC, sanjayparekh-hmcts approved these changes

2024-07-05 09:28 UTC, gokul-sol submitted a review, later dismissed

2024-07-05 11:16 UTC, sanjayparekh-hmcts submitted a review, later dismissed

2024-07-05 11:51 UTC, gokul-sol approved these changes

2024-07-05 11:53 UTC, merged